local dcsHl=require('lfs');dofile(dcsHl.writedir()..'Scripts\\Helios\\HeliosExport16.lua')
local dcsRg=require('lfs');dofile(dcsRg.writedir()..[[Scripts\DCS-raygun.lua]])
local dcsBs=require('lfs');dofile(dcsBs.writedir()..[[Scripts\DCS-BIOS\BIOS.lua]])
local vaicomlfs = require('lfs'); dofile(vaicomlfs.writedir()..[[Scripts\VAICOMPRO\VAICOMPRO.export.lua]])
local Tacviewlfs=require('lfs');dofile(Tacviewlfs.writedir()..'Scripts/TacviewGameExport.lua')
